[project]
name = "docker-socket-proxy"
version = "1.0.0"
description = ""
authors = [{ name = "Tecnativa" }]
requires-python = ">=3.10,<4"


[dependency-groups]
dev = [
    "plumbum>=1.6.9",
    "pytest>=6.1.2",
    "pytest-xdist>=2.1.0",
]

[tool.uv]
package = false

[tool.poetry]
package-mode = false

[tool.pytest.ini_options]
addopts = "-ra -n auto"


[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
